Try to fix smc resampling
effekt-lang/effekt-website pull request #16
Opened 2022-04-13 16:35 UTC by b-studios

Hey @mm0821 could you look into this again? This is a draft implementing what you suggested. However, since we now keep live particles around for resampling the probability of 1 in the geometric distribution is VERY high. I am not sure this is correct...

2022-04-13 16:35 UTC, b-studios commented
@phischu you also might be interested in this.

2022-04-13 20:02 UTC, mm0821 requested changes
With resetting the weights after resampling, this should be correct. The distribution for `biasedGeometric` should be the same as with importance sampling then.

2022-04-13 20:02 UTC, mm0821 commented on docs/casestudies/smc.md
>  Using the `Particle` data type, we can define our SMC handler as follows:
Maybe it is better to write "Using the above data types ...".

2022-04-13 21:09 UTC, b-studios commented
This is how the distribution looks like with 1000 Particles: 
![image](https://user-images.githubusercontent.com/408265/163270745-99e5b5d1-1258-4bf5-b1b9-ca31645dd63f.png)

However, the new resampling is embarrasingly slow.... :D

2022-04-14 14:33 UTC, mm0821 approved these changes

2022-04-14 14:34 UTC, b-studios commented
I'd be very happy to receive any more efficient implementations of resampling ;)

2022-04-14 14:34 UTC, merged