Add basic documentation for the FFI in Effekt
effekt-lang/effekt-website pull request #36
Opened 2023-09-10 11:48 UTC by matthias-dunkel

2023-09-13 12:00 UTC, b-studios requested changes
Hey, thanks for the PR which is very much appreciated! I have a few comments below.

2023-09-13 12:00 UTC, b-studios commented on docs/concepts/FFI.md
> +Effekt implements a Foreign Function Interface (FFI) for the host languages JavaScript and Java. With Effekt’s FFI it is possible to use the host language functions, to model hosts objects, and to us
```suggestion
Effekt implements a foreign function interface (FFI) for the several host languages (JavaScript, ChezScheme, LLVM, SML, etc.). With Effekt’s FFI it is possible to use the host language functions, to model hosts objects, and to use their methods. 

Like the Effekt language, the FFI differentiates between _value types_ and _interface types_, both of which are opaque in a sense that Effekt does not make any assumptions about their semantics.

_Value types_ do not have to be tracked by Effekt and whereas _interface types_ need to be tracked by Effekt.  Interface types often describe objects or resources and can be used to model FFI capabilities. To track any interfaces, one has to define resources which should be tracked by Effekt and let the object live in these resources (see below).
```

2023-09-13 12:00 UTC, b-studios commented on docs/concepts/FFI.md
> +The defintion of an external function is indicated by the keyword `extern` followed by `io`. `io` tells the compiler, that the external function uses the `io` resource, which is tracked by Effekt. Th
Maybe you could explain that `io` is really syntactic sugar for the singleton set `{io}` and `io` is a builtin resource. In general arbitrary resources can be annotated there. Similarly, `pure` is "sugar" for `{}`, and `control` is a special resource used to mark builtins that have access to the continuation (we need a whole section to explain that :) ).

2023-09-13 12:00 UTC, b-studios commented on docs/concepts/FFI.md
> +The definition of an external function is indicated by the keyword `extern` followed by `io`. `io` tells the compiler, that the external function uses the `io` resource, which is tracked by Effekt. T
Here you talk about `io` but the example uses `stack`.

2024-01-26 17:49 UTC, b-studios commented
Hey, do you still plan to contribute this PR?

2024-01-26 18:07 UTC, matthias-dunkel commented
Yes, sorry. The last months were pretty full. I will find some time to contribute in the next week!

2024-01-26 18:32 UTC, b-studios commented
Don't worry, just wanted to check whether I should choose the pr :)

2024-09-09 12:07 UTC, jiribenes commented
Closed for inactivity, a quick intro to current FFI is now in https://github.com/effekt-lang/effekt/pull/536. (cc @dvdvgt)

2024-09-09 12:07 UTC, closed without merging